#!/bin/sh

set -e

cd $HOME

if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
    mkdir -p $HOME/.tmux/plugins
    git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm || true
fi

! grep -q "source ~/.bashrc.custom" ~/.bashrc && echo "source ~/.bashrc.custom" >> ~/.bashrc

rm README.md LICENSE bootstrap.sh